### ISSUE TITLE
How to configure

### ISSUE THREAD

**Issue by liepumartins** [mmtrt/wine-platform-runtime#1]
I have installed some snaps that uses this runtime (irfanview)

Using HiDPI screen and scaling of 175% (configured in KDE), makes wine applications (e.g. irfanview menus) unreadable, because wine still uses 100% scaling.
Regular, non snap, wine would allow to change DPI via config/settings dialog. However this snap version comes without that.

How to achieve this?

**Comment by mmtrt** [comment]
`irfanview.wine winecfg` dpi setting should be under graphics tab.
